// Listing 4.6
// numstr.cpp -- following number input with line input
/*
mixing numeric input with line-oriented string input can cause problem
*/
#include <iostream>
int main()
{
    using namespace std;
    cout << "What year was your house built?\n";
    int year;
    // cin >> year;        // the newline generated by the Enter key is left in the input queue, would be put into var address 
    (cin >> year).get();   // or (cin >> year).get(ch)
    // cin.getline(year, 80); not applicable as the first param has to be char *
    cout << "What is its street address?\n";
    char address[80];
    cin.getline(address, 80);
    cout << "Year built: " << year << endl;
    cout << "Address: " << address << endl;
    cout << "Done!\n";
    return 0;
}